server:
  port: ${PORT:8080}

spring:
  application:
    name: factchecker
  jpa:
    database-platform: ${DATABASE_PLATFORM:org.hibernate.community.dialect.SQLiteDialect}
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

google:
  factcheck:
    api:
      key: ${GOOGLE_FACTCHECK_API_KEY:}
    trusted-publishers:
      - "Aos Fatos"
      - "Lupa"
      - "Agência Lupa"
      - "Estadão Verifica"
      - "UOL Confere"
      - "UOL"
      - "Fato ou Fake"
      - "G1"
      - "O Globo"
      - "CBN"
      - "Projeto Comprova"
      - "AFP Checamos"
      - "AFP Factual"
      - "Reuters"
      - "Reuters Fact Check"
      - "Folha"
      - "Folha de S.Paulo"
      - "BBC News Brasil"
      - "Band"
      - "SBT"
      - "Record"
      - "CNN Brasil"
      - "Veja"
      - "IstoÉ"
      - "Poder360"
      - "Nexo"
      - "Jornal Nacional"
      - "Fantástico"
      - "GloboNews"
