spring:
  application:
    name: factchecker
  datasource:
    url: jdbc:sqlite:db.sqlite3
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

google:
  factcheck:
    api:
      key: "YOUR_API_KEY_HERE"
